function checkered(size: number): string {
  const half = size / 2
  return `[background-color:#333] [background-image:linear-gradient(45deg,#444_25%,transparent_25%),linear-gradient(-45deg,#444_25%,transparent_25%),linear-gradient(45deg,transparent_75%,#444_75%),linear-gradient(-45deg,transparent_75%,#444_75%)] [background-size:${size}px_${size}px] [background-position:0_0,0_${half}px,${half}px_-${half}px,-${half}px_0px]`
}

const btnPrimaryBase = 'h-10 bg-ignition text-white border-none text-xs font-sub font-bold uppercase tracking-widest cursor-pointer transition-colors hover:bg-ignition/90'
const captionLabel = 'font-sub text-xs font-bold uppercase tracking-widest text-muted'

const styles: Record<string, string> = {
  main: 'font-body',
  header: 'mb-8',
  headerTop: 'flex flex-wrap items-start justify-between gap-4',
  btnNewProject: 'h-9 px-3.5 text-xs font-sub font-bold uppercase tracking-widest text-white bg-carbon border border-border cursor-pointer transition-colors shrink-0 hover:bg-white/10',
  title: 'font-heading text-2xl text-white mb-1',
  subtitle: 'text-sm text-muted m-0',
  sessionHint: 'text-xs text-muted mt-2.5 leading-relaxed m-0',
  setup: 'grid grid-cols-1 sm:grid-cols-2 gap-6 mb-6',
  setupBlock: 'flex flex-col gap-1.5',
  vehicleFields: 'grid grid-cols-1 gap-3',
  vehicleActions: 'flex items-center gap-2.5 mt-1.5',
  radioRow: 'flex gap-4 items-center',
  radioLabel: 'flex items-center gap-1.5 text-sm text-white cursor-pointer [&_input]:accent-ignition [&_input]:cursor-pointer',
  styleRow: 'flex items-end gap-4 mt-0.5',
  styleToggleGroup: 'flex gap-1',
  styleToggle: 'w-9 h-9 flex items-center justify-center border border-border bg-carbon text-white text-[15px] cursor-pointer transition-all hover:border-white/30 hover:bg-white/5 disabled:opacity-50 disabled:cursor-not-allowed',
  styleToggleActive: '!border-ignition bg-ignition/10 !text-white',
  styleToggleBold: 'font-extrabold font-serif',
  styleToggleItalic: 'italic font-medium font-serif',
  styleToggleUnderline: 'underline font-medium font-serif',
  shadowSwatchGroup: 'flex flex-col gap-1.5',
  shadowSwatches: 'flex gap-1',
  shadowSwatch: 'w-9 h-9 flex items-center justify-center border border-border bg-carbon cursor-pointer transition-all hover:border-white/30 disabled:opacity-50 disabled:cursor-not-allowed',
  shadowSwatchActive: '!border-ignition bg-ignition/10',
  shadowSwatchOff: '',
  shadowSwatchBlack: '',
  shadowSwatchWhite: '',
  shadowSwatchPreview: 'w-[18px] h-[18px] rounded-full border border-border',
  label: captionLabel,
  input: 'h-10 border border-border bg-carbon px-3 text-sm text-white w-full box-border transition-colors focus:outline-none focus:border-ignition disabled:opacity-50 disabled:cursor-not-allowed',
  hint: 'text-xs text-muted m-0 [&_a]:text-white [&_a]:underline-offset-2',
  uploadZone: 'border-[1.5px] border-dashed border-border min-h-[140px] flex items-center justify-center cursor-pointer bg-carbon transition-colors hover:bg-white/5 hover:border-white/20 overflow-hidden',
  hasImage: '!border-solid !border-border !min-h-0',
  preview: 'w-full h-[300px] object-cover bg-carbon block',
  uploadPlaceholder: 'flex flex-col items-center gap-2 text-muted text-sm',
  uploadIcon: 'text-2xl',
  promptBlock: 'mb-6 flex flex-col gap-1.5',
  textarea: 'border border-border bg-carbon px-3 py-2.5 text-sm font-mono text-white w-full box-border resize-y leading-relaxed transition-colors focus:outline-none focus:border-ignition disabled:opacity-50 disabled:cursor-not-allowed',
  tweakBlock: 'mb-6 flex flex-col gap-1.5',
  actions: 'flex gap-2.5 items-center',
  btnPrimary: `${btnPrimaryBase} px-5 disabled:opacity-35 disabled:cursor-not-allowed`,
  btn: 'h-10 px-4 bg-carbon text-white border border-border text-sm cursor-pointer transition-colors hover:bg-white/10',
  results: 'mt-2',
  resultsTitle: 'text-lg font-heading text-white mb-5',
  grid: 'grid grid-cols-1 md:grid-cols-2 gap-6 items-start',
  tweakPanel: 'flex flex-col gap-4',
  resultSidePanel: 'flex flex-col gap-5 [&_.actions]:mb-0',
  tweakPanelActions: 'flex gap-2.5 items-center',
  tweakHistoryRow: 'flex gap-2 mb-3 overflow-x-auto pb-1 [&::-webkit-scrollbar]:h-1.5 [&::-webkit-scrollbar-thumb]:bg-white/20',
  tweakHistoryItem: 'shrink-0 flex flex-col items-center gap-1 p-1.5 border border-border bg-carbon cursor-pointer transition-all hover:border-white/30 hover:bg-white/5 disabled:opacity-50 disabled:cursor-not-allowed',
  tweakHistoryItemActive: '!border-ignition bg-ignition/10',
  tweakHistoryThumb: 'w-16 h-16 object-contain bg-obsidian',
  tweakHistoryLabel: 'text-[10px] font-sub font-bold uppercase tracking-wider text-white/80 max-w-[80px] truncate',
  collapseToggle: 'inline-flex items-center gap-1.5 w-fit p-0 border-0 bg-transparent text-sm font-semibold text-white cursor-pointer',
  card: 'border border-border overflow-hidden bg-obsidian',
  resultCardSticky: 'md:sticky md:top-[18px] self-start',
  cardHeader: 'py-3.5 px-4 border-b border-border flex items-start justify-between gap-2',
  cardTitle: 'text-sm font-semibold text-white',
  cardTag: 'text-xs text-muted mt-0.5',
  badge: 'text-[11px] font-medium px-2.5 py-0.5 rounded-full whitespace-nowrap shrink-0',
  badgePending: 'bg-carbon text-muted',
  badgeRunning: 'bg-ignition/10 text-ignition',
  badgeDone: 'bg-emerald-500/10 text-emerald-400',
  badgeError: 'bg-redline/10 text-redline',
  cardBody: 'min-h-[460px] max-h-[460px] bg-carbon flex flex-col items-stretch justify-center overflow-hidden max-md:min-h-[360px] max-md:max-h-[360px]',
  errorWithImage: 'w-full self-stretch',
  spinnerWrap: 'flex flex-col items-center justify-center min-h-full gap-3',
  spinner: 'w-7 h-7 border-2 border-border border-t-muted rounded-full animate-spin',
  spinnerText: 'text-sm text-muted m-0',
  resultImg: 'w-full block',
  resultImgWrap: 'w-full leading-[0] max-md:max-w-[360px] max-md:mx-auto',
  checkered: checkered(16),
  approveRow: 'flex flex-wrap items-center gap-3 px-4 py-3 border-t border-border bg-obsidian',
  btnApprove: `${btnPrimaryBase} px-[18px] disabled:opacity-45 disabled:cursor-not-allowed`,
  approveHint: 'text-xs text-muted max-w-[420px] leading-relaxed',
  revThumbCheckered: checkered(8),
  resultFrame: 'relative w-full self-stretch',
  resultFrameComposite: '',
  generatingOverlay: 'absolute inset-0 flex flex-col items-center justify-center gap-3 bg-void/60 backdrop-blur-sm',
  overlayText: 'text-sm text-muted m-0',
  revisionBanner: 'absolute left-0 right-0 bottom-0 px-3 py-2.5 text-xs text-ignition bg-ignition/10 border-t border-ignition/20',
  revisionBar: 'flex items-center justify-center gap-3 px-3 py-2.5 border-t border-border bg-obsidian',
  revNav: 'w-9 h-8 border border-border bg-carbon text-base font-medium text-white cursor-pointer leading-[1] transition-colors hover:bg-white/10 disabled:opacity-35 disabled:cursor-not-allowed',
  revMeta: 'text-xs text-muted max-w-[min(60vw,420px)] overflow-hidden text-ellipsis whitespace-nowrap text-center',
  revisionStrip: 'flex flex-wrap gap-2 px-3 py-2.5 border-t border-border bg-obsidian',
  revThumb: 'relative w-14 h-14 p-0 border-2 border-border overflow-hidden cursor-pointer bg-carbon shrink-0 transition-colors [&_img]:w-full [&_img]:h-full [&_img]:object-cover [&_img]:block hover:border-white/30',
  revThumbActive: '!border-ignition shadow-[0_0_0_1px_theme(colors.ignition)]',
  revThumbLabel: 'absolute bottom-0.5 right-0.5 text-[10px] font-semibold text-white bg-black/55 px-1.5 py-px leading-tight',
  errorText: 'text-xs text-redline p-4 text-center m-0 break-words',
  cardFooter: 'px-4 py-3 border-t border-border',
  cardDesc: 'text-xs text-muted leading-relaxed m-0',
  presetSection: 'mt-10 pt-8 border-t border-border',
  presetSectionInline: '!mt-0 !pt-0 !border-t-0',
  presetSectionTitle: 'text-lg font-heading text-white mb-2',
  presetSectionIntro: 'text-sm text-muted mb-5 max-w-[56ch] leading-relaxed m-0',
  backgroundProgress: 'inline-flex items-center gap-2.5 text-xs text-muted mb-3.5',
  btnBackgroundCancel: 'h-[30px] px-3 border border-border bg-carbon text-white text-xs cursor-pointer hover:bg-white/10',
  presetPicker: 'flex flex-wrap gap-1 mb-6 max-md:grid max-md:grid-cols-3 max-md:gap-2.5',
  presetOption: 'flex flex-col items-stretch w-[105px] p-[2px] border border-white/10 rounded-lg bg-obsidian cursor-pointer overflow-hidden transition-colors hover:border-white/25 disabled:cursor-not-allowed disabled:opacity-60 max-md:w-full max-md:min-w-0',
  presetOptionActive: '!border-ignition',
  presetThumbWrap: 'block w-full aspect-square bg-void rounded-t-md overflow-hidden',
  presetThumb: 'w-full h-full object-cover block',
  presetNoneLabel: 'flex items-center justify-center aspect-square text-sm font-medium text-muted rounded-t-md [background-image:repeating-conic-gradient(#222_0%_25%,#333_0%_50%)] [background-size:16px_16px]',
  presetNewLabel: 'flex items-center justify-center aspect-square text-[28px] font-light text-muted bg-carbon border-b border-white/10 rounded-t-md',
  presetOptionNew: '!border-dashed !border-white/10 hover:!border-white/25',
  presetOptionCaption: 'text-[11px] text-muted px-1.5 py-2 text-center leading-tight',
  presetOptionSub: 'text-[10px] text-muted/60 px-1.5 pb-2 -mt-1 text-center leading-tight',
  customBackgroundPanel: 'max-w-[720px] mb-5 flex flex-col gap-3',
  customBackgroundError: 'm-0 text-xs text-redline',
  compositeBlock: 'mt-2',
  compositeAdjustRow: 'flex flex-wrap items-end justify-start gap-3 mb-2.5 max-md:flex-col max-md:items-stretch max-md:gap-3.5',
  compositeAdjustControl: 'min-w-[260px] flex-1 max-md:min-w-0',
  compositeAdjustHead: 'flex items-center justify-between text-xs text-muted mb-1.5',
  compositeAdjustValue: 'font-semibold text-white',
  compositeAdjustInputRow: 'flex items-center gap-2 [&_input[type=range]]:w-full [&_input[type=range]]:min-w-0 [&_input[type=range]]:accent-ignition',
  compositeNudgeBtn: 'w-8 h-8 border border-border bg-carbon text-white text-lg leading-[1] cursor-pointer hover:bg-white/10 disabled:opacity-45 disabled:cursor-not-allowed',
  compositeLabel: `${captionLabel} mb-2.5`,
  compositeStage: `relative w-full max-w-[720px] mx-auto ${checkered(16)} overflow-hidden border border-border shadow-lg aspect-square touch-none cursor-grab max-md:[touch-action:pan-y_pinch-zoom] max-md:cursor-default`,
  canvasSpaceControls: 'absolute top-2.5 right-2.5 z-[2] flex flex-col items-center gap-1.5 p-1.5 rounded-lg bg-black/80 border border-border backdrop-blur-sm max-md:top-2 max-md:right-2 [&>button]:w-7 [&>button]:h-7 [&>button]:text-base max-md:[&>button]:w-[30px] max-md:[&>button]:h-[30px] max-md:[&>button]:text-lg',
  canvasSpaceValue: 'min-w-[34px] text-center text-[11px] font-semibold text-white',
  compositeCanvas: 'block w-full h-auto',
  textOverlayBlock: 'mt-3.5 border border-border p-3 bg-obsidian',
  textOverlayHeader: 'flex items-center justify-between gap-2.5 mb-2.5 max-md:flex-wrap max-md:items-start',
  textOverlayEmpty: 'm-0 text-xs text-muted',
  textLayerList: 'flex flex-col gap-2',
  textLayerRow: 'flex items-center justify-between gap-2.5 border border-border p-2 bg-carbon cursor-pointer',
  textLayerRowActive: '!border-ignition bg-ignition/5',
  textLayerName: 'text-xs text-white whitespace-nowrap overflow-hidden text-ellipsis',
  textLayerActions: 'flex items-center gap-1.5',
  textLayerEditor: 'mt-3 flex flex-col gap-2.5',
  textLayerGrid: 'grid grid-cols-[1fr_auto] gap-2.5 items-end max-md:grid-cols-1',
  colorInput: 'w-14 h-10 border border-border bg-carbon p-0 cursor-pointer disabled:opacity-55 disabled:cursor-not-allowed',
  textOverlayHint: 'm-0 text-xs text-muted',
  alignBtnRow: 'flex gap-2 mb-2',
  alignBtn: 'h-[34px] min-w-[78px] px-2.5 border border-border bg-carbon text-white text-sm cursor-pointer hover:bg-white/10 disabled:opacity-50 disabled:cursor-not-allowed',
  alignBtnActive: '!border-ignition bg-ignition/10 font-semibold',
  mobileResultDock: `hidden max-md:block fixed right-3.5 bottom-3.5 w-[140px] h-[140px] p-0 border-2 border-ignition overflow-hidden ${checkered(12)} shadow-[0_10px_20px_rgba(0,0,0,0.4)] z-[60] cursor-pointer opacity-0 translate-y-4 translate-x-2.5 pointer-events-none transition-all duration-200 [&_img]:w-full [&_img]:h-full [&_img]:object-contain [&_img]:block max-[380px]:w-[100px] max-[380px]:h-[100px]`,
  mobileResultDockVisible: '!opacity-100 !translate-y-0 !translate-x-0 !pointer-events-auto',
  mockupContainer: 'relative w-full aspect-square bg-carbon border border-border overflow-hidden',
  mockupCanvas: 'absolute inset-0 w-full h-full',
  mockupPrintZone: 'absolute border border-dashed border-white/20 pointer-events-none',
  mockupPlaceholder: 'flex items-center justify-center h-full text-sm text-muted',
}

export default styles
